### ISSUE TITLE
Micronaut launch configuration for R2DBC invalid and blocking driver required for integration to function

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-test-resources#109]
### Expected Behavior

Creating an app with `data-r2dbc` and `mysql` should work

### Actual Behaviour

Doesn't currently work because:

1. The Micronaut Launch generator will populate a URL
2. The blocking mysql JDBC driver is required

Some of this should be fixed in launch but we should automatically add dependencies for test resources when the reactive driver is present but the JDBC driver is not

### Version

3.7.1

**Comment by melix** [comment]
Should this be in `micronaut-starter` instead?

**Comment by graemerocher** [comment]
I am not sure if the issue where the JDBC driver being absent can be fixed in starter

**Comment by melix** [comment]
The thing is either the JDBC driver is required, in which case it should be added to the template that starter uses, or it's not, and then there's something wrong with R2DBC support. I will investigate this from a test resources POV, to check that it's not test resources itself causing that the regular driver is needed.

**Comment by melix** [comment]
So I can confirm this is the same issue as #79, which can be fixed by generating this in starter:

```gradle
plugins {
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.micronaut.application") version "3.6.2"
    id("io.micronaut.test-resources") version "3.6.2"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

dependencies {
    ...
    testResourcesService("mysql:mysql-connector-java")
}

```
