### ISSUE TITLE
init-script-path does not work in 3.7

### ISSUE THREAD

**Issue by sarmbruster** [micronaut-projects/micronaut-test-resources#122]
### Expected Behavior

Assume a file `src/test/resources/db/init.sql` being referred in `application.yml` as 
```
test-resources:
  containers:
    postgres:
      init-script-path: db/init.sql
```
When running e.g. `./gradlew test` that file should be applied to the test database.

### Actual Behaviour

It seems that test-resources server does not inherit the classpath correctly:
```
12:06:30.209 [default-nioEventLoopGroup-1-7] WARN  org.testcontainers.ext.ScriptUtils - Could not load classpath init script: db/init.sql
```

### Steps To Reproduce

see description in Expected Behaviour

### Environment Information

see thread on gitter as well: https://gitter.im/micronautfw/questions?at=6363a25921df5f7a54cfae9d

### Example Application

can share privately if necessary

### Version

3.7.2

**Comment by MT-Jacobs** [comment]
You beat me to it! Here's an example application with a failing test - https://github.com/MT-Jacobs/tr-workshop

**Comment by sarmbruster** [comment]
I case of Gradle being used as build tool this can be resolved by moving the init-script-file from `src/test/resources` to `src/testResources/resources`.

**Comment by MT-Jacobs** [comment]
Oh! Well that's a change in behavior then. I previously had it working fine in the `test` directory.

**Comment by melix** [comment]
Change of behavior compared to using testcontainers directly in your tests, I guess. The difference is that test resources are _not_ executed in the test sources context: they are isolated in their own process (which is a reason why they work fine with native images).

**Comment by MT-Jacobs** [comment]
In any event this can probably be closed as not an issue - the docs in https://github.com/micronaut-projects/micronaut-test-resources/commit/c777980acd25d6f57dc203243fbf802d439d769f clarify this behavior.
