### ISSUE TITLE
Improve Documentation on using JDBC and R2DBC together

### ISSUE THREAD

**Issue by bzolivereckle** [micronaut-projects/micronaut-test-resources#124]
### Issue description

As discussed here (https://github.com/micronaut-projects/micronaut-data/issues/1757) there is no way to figure out by the documentation how to run flyway with jdbc and micronaut data on r2dbc together. 

The documentatation says 

> In which case, the name of the datasource must match the name of the R2DBC datasource. This can be useful when using modules like Flyway which only support JDBC for updating schemas, but still have your application use R2DBC: in this case the container which will be used for R2DBC and JDBC will be the same.

But thats not working. 

We found that https://www.zsiegel.com/2022/01/25/Micronaut-JDBC-R2DBC-Flyway-multiple-schemas but thats quite strange to handle and no very elegant solution.

Great would be to have some example which uses micronaut data on r2dbc together with flyway.
Regards
Oliver

**Comment by graemerocher** [comment]
There is an in progress guide on this topic https://github.com/micronaut-projects/micronaut-guides/pull/965

**Comment by melix** [comment]
Closing as delivered in guides
