### ISSUE TITLE
Allow additional waiting strategy for the Database to be available

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#136]
### Feature description

Unfortunately, there is something different with timing when Rancher Desktop is used which makes Postgres (probably Oracle) container tests fail because it's reported as ready(it uses `LogMessageWaitStrategy`), but it still takes some time for the port to be exposed or something...

It would be nice to have some additional availability checks that can be enabled. I can see two options:

1. Await for successful SQL query, that is the default Testcontainers check:
https://github.com/testcontainers/testcontainers-java/blob/7ba6b1c518d8f181b5831229977c260dbff803dc/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java#L143-L175
Unfortunately, it's overridden by Postgres and Oracle with `LogMessageWaitStrategy`.
This check might be the most bulletproof but might need a custom configuration of the SQL check query.

2. Wait for the port to be available. We can probably reuse Testcontainer's `HostPortWaitStrategy`.

**Comment by melix** [comment]
Relates to #123

**Comment by kiview** [comment]
Just chiming in with some experiences:
> This check might be the most bulletproof but might need a custom configuration of the SQL check query.

One would think so, but it is explicitly flaky in the case of the default PostgreSQL image. This originates from the fact, that the PostregeSQL database restarts after bootstrapping its internal tables if the database was started without a data directory being present. This allowed for a small window of a race condition, where the JDBC query would succeed, but the database engine would proceed to perform the restart. The `LogMessageWaitStrategy` was introduced as a more stable criteria for readiness and from our experience, it works more reliably in the case of PostgreSQL.

Regarding the different behavior, I like to point to this comment:
https://github.com/testcontainers/testcontainers-java/issues/5986#issuecomment-1275496406

Rancher Desktop has vastly different runtime characteristics compared to Docker Desktop and Testcontainers does not plan to support them explicitly. 

That being said, for the issue at hand, using `WaitAllStrategy` can be a way to check for multiple indicators of readiness.

**Comment by dstepanov** [comment]
@kiview Great insights! Maybe you can suggest what would be the solution to it. @melix created a PR for custom wait strategies https://github.com/micronaut-projects/micronaut-test-resources/pull/141
