### ISSUE TITLE
Test resource creation 

### ISSUE THREAD

**Issue by pbthorste** [micronaut-projects/micronaut-test-resources#159]
### Feature description

Currently - test resources are created in reaction to a missing property in configuration. Would it be possible to modify this behaviour a bit ? Here is an example:

Config file:
```shell
src/main/resources/application.yml
```
contents:
```yaml
redis:
  uri: ${MY_REDIS_URI} # test resources will only load redis if this line is not set
```

In my application, it is quite inconvenient to not set the "redis.uri" value at all, and so far that is the only way I have managed to make the test resources run redis.

Would it be possible to also trigger test resources to be created if they are set to 'null' in the config ?
Example:
Config file:
```shell
src/test/resources/application-test.yml
```
contents:
```yaml
redis:
  uri: null
```

**Comment by melix** [comment]
This cannot be implemented easily with the current Micronaut core infrastructure. Also `null` can be quite ambiguous in configuration. The closest would probably the initial setup you have, which is if a placeholder cannot be resolved, then fallback (but again this needs changes in `core` which I'm not sure are possible).

Can I ask why it's inconvenient in your case? Typically what we would recommend is that you simply have an `application-prod.yml` file in addition to your `application.yml` file, then start your application with the `prod` environment in production (e.g by setting the `MICRONAUT_ENVIRONMENTS` environment variable).

**Comment by pbthorste** [comment]
Thanks for the info @melix. Too bad that this is not something that can be added without alot of effort.

With regards to why it does not work for me, it is because in my projects, we always only have one `application.yml` file. The values in it are controlled by environment variables which are injected at deploy time. Having a separate `application.yml` per environment would be alot of maintenance because we have so many different environments.

The reason why I though maybe setting the configuration property to null would be an option is that in my current setup, if I set the redis uri to null, i.e.

```yml
redis:
  uri: null
```
I get this error:
```
Message: Failed to inject value for parameter [uri] of method [setUri] of class: io.micronaut.configuration.lettuce.DefaultRedisConfiguration

Message: Error resolving property value [redis.uri]. Property doesn't exist
```
which I though was actually promising because this is exactly what I wanted, but still it did not activate the test resources to start redis.

**Comment by gnarroway-bullish** [comment]
@pbthorste how did you end up working around this?
