### ISSUE TITLE
Initial set of features

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-test-resources#17]
### Issue description

This issue lists the minimal set of features that we want to have before releasing 1.0.

## Features

- [x] Ability to have test resources support _in process_
- [x] Test Resources server
    - [x] Single build use
    - [x] Continous build use
    - [x] Standalone mode (running in background, shared between builds)
    - [x] Shared mode (shared between independent projects)   
- [x] Secure test resources server with access token and restrict to loopback 
- [x] [Gradle plugin](https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/478)
- [x] [Maven plugin](https://github.com/micronaut-projects/micronaut-maven-plugin/pull/398)

## Modules

- [x] Generic test containers support
   - [x] Declarative way to spawn generic test containers
   - [x] Expose ports and host names
   - [x] Support for FS bind (rw and ro)
   - [x] [Copy file to container](https://github.com/micronaut-projects/micronaut-test-resources/pull/20)
   - [x] [Tweak memory size](https://github.com/micronaut-projects/micronaut-test-resources/pull/27)
- [x] Kafka module
- [x] Neo4j module
- [x] MongoDB module
- [x] HiveMQ module
- [x] [RabbitMQ module](https://github.com/micronaut-projects/micronaut-test-resources/pull/19)
- [x] [Redis module](https://github.com/micronaut-projects/micronaut-test-resources/pull/21)
- [x] [ElasticSearch module](https://github.com/micronaut-projects/micronaut-test-resources/pull/23)
- [x] [Hashicorp Vault module](https://github.com/micronaut-projects/micronaut-test-resources/pull/34)
- [x] Databases
   - [x] MySQL
       - [x] JDBC
       - [x] Reactive  
   - [x] PostgreSQL
       - [x] JDBC
       - [x] Reactive  
   - [x] MariaDB
       - [x] JDBC
       - [x] Reactive  
   - [x] SQL Server  
       - [x] JDBC
       - [x] Reactive  
   - [x] Oracle XE       
       - [x] JDBC
       - [x] Reactive

**Comment by dstepanov** [comment]
I would add rabbitmq support for V1, it's one of the Micronaut modules and also supported by the testcontainers.

An interesting use-case would be to support this setup of Kafka https://github.com/micronaut-projects/micronaut-kafka/blob/master/tests/tasks-sasl-plaintext/src/test/groovy/example/TasksSpec.groovy

**Comment by morki** [comment]
The Redis support would be cool two, there is `micronaut-redis` module too.

**Comment by graemerocher** [comment]
yeah I agree we should support Redis

**Comment by melix** [comment]
Thanks @LarsEckart ! Yes, I've seen Localstack and still thinking how to best integrate that. Basically need to look at how some guides could be rewritten to use that.
