### ISSUE TITLE
Enable/Disable Test-Resource server during run task

### ISSUE THREAD

**Issue by francesco-monorchio** [micronaut-projects/micronaut-test-resources#185]
### Feature description

I would like to have the ability to enable/disable test-resource server when I do Gradle "run" task.

Could be added a property like "test-resources.enabled=false" in application.properties for example.
Is this possible? Thanks

**Comment by melix** [comment]
Can you clarify your use case?

**Comment by francesco-monorchio** [comment]
Yes, sure.

When I run my applications in development mode (aka "run" Gradle task), I use another Gradle plugin that spin up containers using docker-compose. It's more simple and practical IMHO and I don't need to replace placeholders because I use a specific environment to connect the these containers. So I don't want to spin up the test-resource server too in this particular case. So I think that it is better to give the developers the opportunity to disable it through configuration.

**Comment by melix** [comment]
mmm, if you are using something else, why are you applying the test resources plugin? You can simply remove it. Or, you can disable test resources in the build script:

```gradle
micronaut {
    runtime("netty")
    ...
    testResources {
        enabled.set(false)

    }
}
```

You can even enable by system property, for example:


```gradle
micronaut {
    runtime("netty")
    ...
    testResources {
         enabled.set(providers.systemProperty("testResources").map(Boolean::parseBoolean).orElse(false)
    }
}
```

**Comment by francesco-monorchio** [comment]
I use it for testing only.

If I add your code block, Gradle fails. I will share a sample repo in the next few days to replicate the problem.

**Comment by francesco-monorchio** [comment]
This is similar to my use case!
https://github.com/francesco-monorchio/micronaut-bugreport/tree/test-resources

**Comment by glubo** [comment]
I also would love to be able to easily support "just for tests" mode. My usecase is that I often need not so trivial data (~GBs) in my database to reproduce some performance issues that won't reproduce on a small database, so it is much more convenient for me to run my own long term database outside of test containers for development.

I would be glad if I can easily configure micronaut test resources to run just for tests, e.g.
- `java -jar ...` => no test resources
- `./gradlew run` => no test resources
- `./gradlew test` => test resources

**Comment by melix** [comment]
Can't you simply use an environment for this? e.g:

```
MICRONAUT_ENVIRONMENTS=dev ./gradlew run
```

Then have an `application-dev.properties` with your DB coordinates.

**Comment by glubo** [comment]
I might be missing something :)

While this is working workaround (thanks for that), it feels against 12-factor application principles (https://12factor.net/config) and inversion of control because when I have `application-dev.properties` instead of db connection in just `application.properties` would I not need also  `application-prod.properties`?

**Comment by melix** [comment]
You definitely need `application-prod.properties`. The `application.properties` file contains the common properties, for development and production. It doesn't contain the DB connection properties, because they differ between test and production. When you use test resources, it creates them for you (and spawn containers, etc). When you're in production, then you need to provide them in some way, either via a `-prod` configuration file, or via environment variables. So your use case is similar to a preprod environment where the DB parameters are already known. Test resources are there to "fill in the blanks", so if you don't want it to kick in, you need to fill the blanks.

**Comment by glubo** [comment]
Oh, so if I don't want to use multiple properties files, I should be able to drive whether test resources are created via environmental variables? This sounds like a way to still be 12-factor (no environmental config in app) and use test containers. Thanks for the hint, I will explore it if it's "the way" for my situation :)

**Comment by melix** [comment]
I'll close this issue as won't fix for now. If there's a use case which cannot be covered by environments, feel free to reopen.

**Comment by yibo-long** [comment]
Several use cases that we couldn't walk around with environment properties:
1. We split our tests into unit tests by running `test`, and integration tests by running `integrationTest`. We would only want to run integration tests with test resources; while it's impossible for us to not mention a fake DB/Kafka related properties in unit test's application-test.yml;
2. We have our own custom test resources with running internal containers and containers that are not available in the repo. Not all of them can have getRequiredProperties. For example of here [localstack] doesn't have it configured either.

It will be helpful if we can provide a config to mark several specific tasks to depend on testResource in gradle plugin. For example like:

```
micronaut {
    testResources {
        additionalModules.add(LOCALSTACK_SQS)
        dependentTestTasks.add("test")
        dependentExecTasks.add("run")
    }
}
```

**Comment by scprek** [comment]
FYI Kotlin version and we are using the jvm test suite plugin

```kotlin
micronaut {
    testResources {
        sharedServer.set(true)
        enabled.set(System.getProperty(MICRONAUT_TEST_RESOURCES_ENABLED)?.toBoolean() ?: true)
    }
}
    
 tasks { 
     named<Test>("contractTest") {
        // Disable Pact Telemetry
        //See: https://docs.pact.io/telemetry#opt-out
        systemProperty("pact_do_not_track", "true")
        // We do not want contract test to start up test containers
        systemProperty(MICRONAUT_TEST_RESOURCES_ENABLED, "false")
    }
 }
 ```

**Comment by distinctdan** [comment]
Yeah this is pretty annoying. We use a local DB for when running locally and test resources spins up stuff even though there's no need. Our server works fine running locally, so test-resources shouldn't be starting containers and slowing everything down. The whole idea of starting up containers to fill missing resources implicitly is a bad design. Containers should only be started explicitly to prevent useless waste like this. However, for now, a flag to enable it only for tests would be fine.

**Comment by melix** [comment]
Test resources is lazy. It will only start a container if it is asked to do so, that is to say that a property is missing and that it can provide it.

**Comment by distinctdan** [comment]
I know it's supposed to be lazy, but I've never found that to be the case. Looking at the logs, it looks like it's taking a couple of seconds to start up even with no missing dependencies, like I'm seeing logs `Creating container for image: testcontainers/ryuk:0.11.0`. It may only be a couple of seconds, but it adds up over the course of the day, and it's log noise.

**Comment by graemerocher** [comment]
IMO we should fix this and have at least a system property that can be passed to the application to disable it

**Comment by melix** [comment]
Well, we can add a system property, but it looks like a code smell. We should figure out why it's not lazy as it should.
