### ISSUE TITLE
Error if applied to subproject

### ISSUE THREAD

**Issue by SenorPez** [micronaut-projects/micronaut-test-resources#206]
### Expected Behavior

Gradle test-resources plugin should successfully apply.

### Actual Behaviour

Gradle build fails with error.

```
Could not resolve all dependencies for configuration ':XXX:testRuntimeClasspath'.
Cannot query the value of extension 'testResources' property 'enabled' because it has no value available.
The value of this property is derived from:
  - extension 'micronaut' property 'version'
```

### Steps To Reproduce

1. Create new empty project with test-resources:

```
applicationType: default
defaultPackage: example.micronaut
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [annotation-api, app-name, data, data-mongodb-reactive, gradle, http-client, jackson-databind, java-application, junit, logback, micronaut-build, netty-server, reactor, reactor-http-client, readme, shade, spring-boot-java, testcontainers, yaml]
```

2. Build Gradle project. It builds successfully.

3. Configure above project as Gradle subproject

4. Build Gradle project. Error occurs.

### Environment Information

OS: Tested on AWS and Windows
Java Version 17

### Version

3.8.8

**Comment by melix** [comment]
I cannot reproduce with Gradle plugin 3.7.10 and Micronaut 3.9.4. If you are still facing this issue, please try to ugprade to the latest Gradle plugin version (3.7.x for Micronaut 3.x) and reopen.

https://scans.gradle.com/s/dnspytqnqhfuk/tests/overview
