### ISSUE TITLE
why placeholder ${auto.test.resources.datasources.default.url} can't be solved for my integration test?

### ISSUE THREAD

**Issue by yuhuaz** [micronaut-projects/micronaut-test-resources#382]
### Issue description

I have a service using  postgreSQL. In my application.yml I have this setting:
_datasources:
  default:
    url: 'jdbc:postgresql://${DATABASE_HOST}:5432'
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES_

In my application-test.yml for integration test,  the datasources setting is overwritten by:
_datasources:
  default:
    url: jdbc:tc:postgresql:14.8:///postgres
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    dialect: POSTGRES_

The integration test works well. Then I tried another way to set test config by using supported module postgres.
I put in gradle plugins:
_plugins {
    id 'io.micronaut.minimal.application' version '4.0.0'
    id 'io.micronaut.test-resources' version '4.0.0'
}_
and add in application-test.yml
_test-resources:
  containers:
    postgres:
      image-name: postgres:14.8_

 I comment out datasources setting from application.yml, the integration test works. That says, the supported module postgres works.  But removing datasources setting from application.yml is not the real  solution.  I consequently uncomment application.yml and overwrite datasources setting in application-test.yml:

_datasources:
  default:
    url: ${auto.test.resources.datasources.default.url}
    driverClassName: org.postgresql.Driver_

Then I get error: _"Message: Could not resolve placeholder ${auto.test.resources.datasources.default.url}
Path Taken: DatasourceFactory.dataSource(DatasourceConfiguration datasourceConfiguration) --> DatasourceFactory.dataSource([DatasourceConfiguration datasourceConfiguration])
at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)"_

I don't understand why this error comes out. My thought is: test resource server for postgres starts if Micronaut framework context detects test-resources.containers.postgres. Once the PostgreSQL server is ready, the Test Resource Server mechanism generates the necessary connection information. This includes the url to connect to the database. This information is then stored as a system property or environment variable.  'auto.test.resources.datasources.default.url'  has value so that  datasources.default.url is overwritten by the real url of the test container.  

Then I add plugin in build.gradle.kts
Micronaut {
    testResources {
        additionalModules.add(JDBC_POSTGRESQL)
    }
}

Then the error goes away and integration test works. 

 I guess the previous error is due to timing issue: When micronaut framework is trying to generate datasource bean from datasources.default.url: ${auto.test.resources.datasources.default.url}, the test resource server hasn't set ‘auto.test.resources.datasources.default.url’ into the application's environment, so we get "Could not resolve placeholder ${auto.test.resources.datasources.default.url}" error.  Adding JDBC_POSTGRESQL into plugin makes test resource server starts up early so the micronaut framework is able to resolve ${auto.test.resources.datasources.default.url} for datasources.default.url.

Is my guess about the timing issue correct or not?

Now back to my initial problem: If I want to use the micronaut supported JDBC (postgres) module  in integration test,  what is the best way to use auto started postgres test container's URL to overwrite datasources.default.url?

**Comment by melix** [comment]
Latest test resources versions provide more information in case of a failure. I'm closing this but if the problem still arises feel free to reopen.
