### ISSUE TITLE
Outdated dependencies in 1.2.5

### ISSUE THREAD

**Issue by codepitbull** [micronaut-projects/micronaut-test-resources#398]
### Expected Behavior

There should be a maintenance branch for the older version which is used for Micronaut 3.

### Actual Behaviour

The current 1.2.5 for micronaut 3 contains a few outdated dependencies.
I wanted to privde a PR with updated dependencies but couldn't find a maintenance branch.

### Steps To Reproduce

Branches drop-down in Git-UI :)

Sorry, I couldn't find a better fitting ticket-type.

I didn't want to file the CVE-report because I think there should still be a maintenance path for this until Micronaut 3 is officially EoL.

### Environment Information

Git

### Version

3.10.1

**Comment by melix** [comment]
There's a `1.2.x` branch for 1.2.x, but indeed it hasn't been updated for a while.

**Comment by codepitbull** [comment]
I am so sorry.
I blame caffeine deficiency for overlooking it.
You are perfectly right.
Should I provide a PR or is that something you are handling?

**Comment by melix** [comment]
Would be great if you provide a PR!

**Comment by codepitbull** [comment]
Would love to, but need a pointer:
I was trying to follow the CONTRIBUTING.md but running 
`./gradlew check` produces:
```* What went wrong:
Could not resolve all files for configuration 'classpath'.
> Could not find null:groovydoc-gradle-plugin:null.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/null/groovydoc-gradle-plugin/null/groovydoc-gradle-plugin-null.pom
    - https://repo.maven.apache.org/maven2/null/groovydoc-gradle-plugin/null/groovydoc-gradle-plugin-null.pom
  Required by:
      unspecified:unspecified:unspecified > io.micronaut.build.shared.settings:io.micronaut.build.shared.settings.gradle.plugin:5.4.5 > io.micronaut.build.internal:micronaut-build:5.4.5 > io.github.groovylang.groovydoc:io.github.groovylang.groovydoc.gradle.plugin:1.0.1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
````

I can't find any further docs on what to do.
Any idea what I am missing?

**Comment by codepitbull** [comment]
Sorry for pestering you, but I really don't know where to go from here.

**Comment by wetted** [comment]
@codepitbull 

I don't know what branch you are trying to build, but it looks like you need to update the version of the micronaut build plugin in `settings.gradle`. That will fix the problem with the unresolvable plugin.

```
plugins {
    id 'io.micronaut.build.shared.settings' version '6.5.6'
}

```

For Micronaut 3.x that would be `.5.4.10` and for Micronaut 4.x it is `6.5.6`.

**Comment by codepitbull** [comment]
@wetted thank you!! That solved it :)
Will test everything and there will be a PR tomorrow!

**Comment by codepitbull** [comment]
Here is the PR:
https://github.com/micronaut-projects/micronaut-test-resources/pull/407

I just can't sign the CLA ... the page seems broken:
https://cla-assistant.io/melix/micronaut-test-resources

**Comment by codepitbull** [comment]
Now it worked.

**Comment by codepitbull** [comment]
What's the state on this?

**Comment by melix** [comment]
I was quite busy for the past 2 weeks. I'm trying to get the `1.2.x` branch passing.
