### ISSUE TITLE
Support configuring R2DBC pool

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-test-resources#41]
### Feature description

It would be nice if the pooling was preconfigured if the pool dependency is on the classpath:

See how is it configured:
https://github.com/micronaut-projects/micronaut-data/blob/65ba1de507b0170194f63f17d8d654fa67c9b709/data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/DatabaseTestPropertyProvider.groovy#L105

**Comment by melix** [comment]
So if the `io.r2dbc:r2dbc-pool` dependency is present, you want the R2DBC test resources resolver to set the `r2dbc.datasources.xxx.options.protocol` and `r2dbc.datasources.xxx.options.driver` properties?

**Comment by dstepanov** [comment]
Yea
