### ISSUE TITLE
Allow specifying a fixed test resources service port for both client and server to use

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-test-resources#441]
### Feature description

Currently we have this automagical port assignment the test resources port written to a file which is then detected by the client dynamically.

It would be frankly easier to simply allow the user to specify a port to use for the service in a `USER_HOME/.micronaut/testresources.properties` file or something so it is local to just the user.

I find myself constantly starting and stopping the service to try and get Maven tests running which is not a great user experience.

**Comment by melix** [comment]
You can use the `explicitPort` feature in the Gradle plugin.

**Comment by graemerocher** [comment]
Ok this works, just need something like https://github.com/micronaut-projects/micronaut-test-resources/issues/443 IMO
