### ISSUE TITLE
@TestResourcesProperties not fetching datasources.default.url value

### ISSUE THREAD

**Issue by noeliajimenezg** [micronaut-projects/micronaut-test-resources#552]
### Expected Behavior

To fetch the value of datasources.default.url when using the annotation @TestResourcesProperties in order to use the value before starting the application.

### Actual Behaviour

@TestResourcesProperties runs before the starting of the container and the value is of datasources.default.url is null.

### Steps To Reproduce

gradle test --debug >> debug.log

### Environment Information

Mac OS

### Example Application

https://github.com/noeliajimenezg/micronaut_error_testresources/tree/main

### Version

4.3.5-SNAPSHOT

**Comment by scprek** [comment]
Yeah, I'm confused by the [docs](https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/#extensions-core) and wondering if the example assumes the rabbitmq resource was force started via the gradle properties `additionalModules` or the values are all static and already there to access?

**Comment by melix** [comment]
There is indeed something strange going on, I can reproduce the problem locally.
