### ISSUE TITLE
Test resources service is shutdown before on-demand configuration and never restarted

### ISSUE THREAD

**Issue by npiguet** [micronaut-projects/micronaut-test-resources#616]
### Expected Behavior

When my webapp is recompiled due to a change in the code, my application *and all the containers it depends on* are restarted.

### Actual Behaviour

When my webapp is recompiled due to a change in the code, it restarts. However all the containers started by Micronaut are shut down and never restarted, causing the application to crash.

### Steps To Reproduce

- I start my application in the local environment using `mvn mn:run -Dmicronaut.environments=test,local`
- My application as well as all the required DB containers are started
- I change something in my code (for example, a minor detail in a .jte file)
- Micronaut prints this in the logs:
```
INFO] 📝 Detected change in src/main/resources/application-test.yml. Recompiling/restarting...
[INFO] [info] Shutting down Micronaut Test Resources service
```
- The application is stopped.
- All the test containers are stopped.
- The application is restarted, but crashes because it can't resolve the `url` property of one of my data sources (which makes sense, since it looks like the test resources service was stopped)

### Environment Information

JDK 17
Ubuntu 22.04

### Version

 4.4.2

**Comment by npiguet** [comment]
This might actually be a micronaut-maven-plugin issue.

**Comment by alvarosanchez** [comment]
Closed in favour of https://github.com/micronaut-projects/micronaut-maven-plugin/issues/1100
