### ISSUE TITLE
Test-Resource server as standalone module not resolve properties for MongoDB and Kafka

### ISSUE THREAD

**Issue by fmonorchio** [micronaut-projects/micronaut-test-resources#89]
### Expected Behavior

When I ran the Test-Resource service as standalone module it should resolve properties for MongoDB and Kafka but I receive this error:

> io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.data.mongodb.transaction.TransactionalClientSession$Intercepted] could not be loaded: Error instantiating bean of type  [com.mongodb.MongoClientSettings]
> 
> Message: Could not resolve placeholder ${MONGODB_URI}

Server seems that is running and load these 3 resources resolvers correctly: io.micronaut.testresources.kafka.KafkaTestResourceProvider, io.micronaut.testresources.mongodb.MongoDBTestResourceProvider, io.micronaut.testresources.testcontainers.GenericTestContainerProvider

### Actual Behaviour

Properties mongodb.uri and kafka.bootstrap.server are not resolved during integration tests.

### Steps To Reproduce

Run "./gradlew check"

### Environment Information

OpenSuse Tumbleweed
Jdk 17.0.4

### Example Application

https://github.com/fmonorchio/micronaut-test-resources-error

### Version

3.6.1

**Comment by melix** [comment]
A quick look at your sources (unusual setup!) shows that you have this line in your configuration file: https://github.com/fmonorchio/micronaut-test-resources-error/blob/main/sources/user-service/src/main/resources/application.yml#L6

Test resources only work if you _don't_ set a value for the MongoDB URI, so you should remove this line, and have a separate configuration file for production instead (say `application-prod.yml`) if you want to pass de value via an env var.

**Comment by fmonorchio** [comment]
Sorry for my unusual setup but I have cleanup all other modules that are not needed for this error to appears :-)

So, I have moved all properties with env vars to -prod.yml as you said and its ok. Thanks @melix
