### ISSUE TITLE
Adding additional database support via AbstractJdbcTestResourceProvider - not supported, insufficiently documented, or is this implementation wrong?

### ISSUE THREAD

**Issue by MT-Jacobs** [micronaut-projects/micronaut-test-resources#94]
### Issue description

I aim to add support for a new database (CockroachDB) to Micronaut Test Resources. I can't just use a GenericTestContainerProvider as I need a AbstractJdbcTestResourceProvider to provide all of the database properties. To make this work, I implemented my own AbstractJdbcTestResourceProvider.
According to the docs: https://micronaut-projects.github.io/micronaut-test-resources/1.1.1/guide/index.html#implementing-test-resources

In addition, you need to declare the resolver for service loading, by adding your implementation type name in the `META-INF/services/io.micronaut.testresources.core.TestResourcesResolver file.

which, for my kotlin project, sounds like this file belongs in `{module}/src/test/resources/META-INF/services/`.
However, the logs indicate that this resolver wasn't loaded:

```
[36m15:23:10.694[0;39m [1;30m[ForkJoinPool.commonPool-worker-9][0;39m [34mINFO [0;39m [35mi.m.t.e.TestResourcesResolverLoader[0;39m - Loaded 4 test resources resolvers: io.micronaut.testresources.postgres.PostgreSQLTestResourceProvider, io.micronaut.testresources.redis.RedisTestResourceProvider, io.micronaut.testresources.elasticsearch.ElasticsearchTestResourceProvider, io.micronaut.testresources.testcontainers.GenericTestContainerProvider
```

My best guess is that I'm running a Micronaut Test Resources server, the only documented way to use test resources; the embedded server version is mentioned but there are no details on how to run it. If that's the case, it's possible that the test resources server doesn't have visibility on my module's META_INF.

All that context given,

What am I doing wrong here?; or
What is the right way to debug the test resources server to figure out this problem myself?

**Comment by melix** [comment]
> which, for my kotlin project, sounds like this file belongs in `{module}/src/test/resources/META-INF/services`/.
However, the logs indicate that this resolver wasn't loaded

Test resources _must not_ be defined in the test source set: they are executed in a separate process from tests, and therefore are compiled separately. If you use Gradle, which I assume is the case because you're using Kotlin, your test resource can be implemented in the `src/testResources/java` source set: https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_implementing_your_own_test_resources_resolver

**Comment by MT-Jacobs** [comment]
Ah, that makes perfect sense! Thank you so much! I'll test that out today.

For the time being, I proposed a minor documentation change - https://github.com/micronaut-projects/micronaut-test-resources/pull/95. It doesn't so much beyond more directly call out that each plugin has its own Test Resources-specific documentation.

**Comment by melix** [comment]
I can improve the docs to mention in the implementation section that it is likely that the test resources are going to be invoked in a separate process.
